# Formulario para reportar errores (bugs).
# Guía al usuario para aportar la información necesaria.

name: '🐞 Informe de bug' # Título del tipo de issue
description: Reporta un error o comportamiento inesperado
title: '[BUG] ' # Prefijo sugerido para el título del issue
labels: ['bug'] # Etiqueta automática aplicada al crear el issue
body: # Campos del formulario
  - type: checkboxes
    id: duplicates
    attributes:
      label: Duplicados
      description: ¿Comprobaste si ya existe un issue similar?
      options:
        - label: He revisado issues abiertos y cerrados
          required: true
  - type: input
    id: version
    attributes:
      label: Versión / commit
      placeholder: 'v0.1.0 o SHA corta (abcd123)'
  - type: input
    id: env
    attributes:
      label: Entorno
      placeholder: 'SO, VS Code, stack (si aplica)'
  - type: textarea
    id: steps
    attributes:
      label: Pasos para reproducir
      placeholder: "1. Clonar\n2. Ejecutar X\n3. Ocurre Y"
      render: markdown
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Resultado esperado
  - type: textarea
    id: actual
    attributes:
      label: Resultado actual
  - type: textarea
    id: screenshots
    attributes:
      label: Evidencias (capturas/logs)
  - type: dropdown
    id: severity
    attributes:
      label: Severidad
      options: [baja, media, alta, bloqueante]
      default: 1
  - type: textarea
    id: extra
    attributes:
      label: Notas adicionales
